CREATE OR ALTER FUNCTION formatar_cnpj(@STRING VARCHAR(14))
RETURNS VARCHAR(18)
AS
BEGIN

	DECLARE 
		@FIRST_PART		 VARCHAR(2),
		@SECOND_PART	 VARCHAR(3),
		@THIRD_PART		 VARCHAR(3),
		@FOURTH_PART	 VARCHAR(4),
		@LAST_PART		 VARCHAR(2),
		@STRING_FORMATED VARCHAR(18)
		
		SET @FIRST_PART = LEFT(@STRING, 2)
		SET @SECOND_PART = SUBSTRING(@STRING, 3, 3)
		SET @THIRD_PART = SUBSTRING(@STRING, 6, 3)
		SET @FOURTH_PART = SUBSTRING(@STRING, 9, 4)
		SET @LAST_PART = RIGHT(@STRING, 2)
		SET @STRING_FORMATED =  @FIRST_PART + '.' + @SECOND_PART + '.' + @THIRD_PART + '/' + @FOURTH_PART + '-' + @LAST_PART

	RETURN @STRING_FORMATED

END
GO