CREATE OR ALTER FUNCTION remover_caracteres_cpf_cnpj(@STRING VARCHAR(20))
RETURNS VARCHAR(20)

BEGIN

	DECLARE @STR_FORMATED VARCHAR(14)

		SET @STR_FORMATED = REPLACE(REPLACE(REPLACE(REPLACE(@STRING, ' ', ''), '-', ''), '.', ''), '/', '')

	RETURN @STR_FORMATED

END
GO